### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by twixwix** [svewap/zabbix_client#1]
Would be great to have a step-by-step how to integrate it in Zabbix.
How and where can we get the API String....

Thx

**Comment by twixwix** [comment]
Could you maybe place some sceenshots of how to configure the zabbix.

**Comment by svewap** [comment]
I need some free time for the documentation of this side project ;-)
It will come!

**Comment by twixwix** [comment]
Sorry for the annoying behavior but I am looking for a long time for such a function.

**Comment by svewap** [comment]
Do you still have a zabbix server running?

**Comment by twixwix** [comment]
Of course I have one running as productive server with the typo3.xml file on it.

**Comment by svewap** [comment]
I enhanced the doc: https://docs.typo3.org/p/wapplersystems/zabbix_client/master/en-us/

**Comment by twixwix** [comment]
Thank you very much worked perfectly. How does it take unti the Typo3 Values are getting filled?

- I think the custom key which was created in the macro area would be the same as in typo3 extension configuration.
- Which charakters are allowed in the key?

![2019-10-20 14_18_18-Window](https://user-images.githubusercontent.com/5329006/67159416-9a167700-f344-11e9-8884-192dff26e3a3.png)

**Comment by svewap** [comment]
In Zabbix you can do a "Check now" manually. Just go in the "Item" View of the host, select all and push the "Check now" button. You can also change the intervals like you want.
All keys should be send as a POST Request, so you should be able to use all characters you want.

**Comment by twixwix** [comment]
perfect many thanks its working now. 
This is an awesome work great job.

**Comment by svewap** [comment]
Great. Please share. Feedback and suggestions are welcome. I'm building a website for this project: https://www.t3monitoring.de/
