### ISSUE TITLE
Zabbix 4.0.x

### ISSUE THREAD

**Issue by chris246** [svewap/zabbix_client#10]
Hi,

Debian's repositories currently only provide Zabbix 4.0.x.
It would be great, if you could provide a template compatible with this version.

**Comment by svewap** [comment]
Hello,
unfortunately I don't have old versions and can't check this even for time reasons. I always try to use the newest versions.
Maybe you can build new packages with the OpenSuse Build Service. This service also supports Debian.
https://build.opensuse.org/

**Comment by chris246** [comment]
Ok.
I like to use the official packages ;)

I'll try to backport the template for Typo3 v9+ and create a merge request.

**Comment by svewap** [comment]
Zabbix 4 is very old now. I'm closing this issue. Zabbix is now available in many forms, including docker image.
