### ISSUE TITLE
Wrong Position in Middleware Stack

### ISSUE THREAD

**Issue by TheJotob** [svewap/zabbix_client#11]
I just found out, that the position in the middleware stack before typo3/cms-frontend/tsfe is fine for version 9 but fails in version 10, since the TSFE Middleware moved down after the page-resolver. So that the URL "/zabbixclient/" returns a 404 since the page-resolver can't resolve the url.
The easiest way would be to move it before page-resolver, but then it might not work in Version 9, because I'm sure there is a reason it was located before TSFE.
So either there needs to be a version check in the RequestMiddlewares.php or we have to put it before the eID Middleware or something like that.
What do you think?
If we have a decision I will gladly provide a PR for it :)

**Comment by svewap** [comment]
Hi. I will look at it as soon as possible.

**Comment by svewap** [comment]
Solved
