### ISSUE TITLE
Usage of undefined constants in GetExtensionList

### ISSUE THREAD

**Issue by r3h6** [svewap/zabbix_client#12]
In TYPO3 v10, the constants PATH_typo3conf and PATH_typo3 are not defined anymore.
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85285-DeprecatedSystemConstants.html

**Comment by svewap** [comment]
Is fixed in next release
https://github.com/svewap/zabbix_client/commit/c82a8d2c09e9b6a8661182d8b007845783d4327f
