### ISSUE TITLE
Update trough Zabbix?

### ISSUE THREAD

**Issue by twixwix** [svewap/zabbix_client#2]
Would it be possible to trigger an update from Zabbix with your agent on typo3?

**Comment by svewap** [comment]
This is theoretically possible. Of course it would have to be programmed.
But actually Zabbix should only be a monitoring tool that observes and does not trigger anything.
It would be better if you define a cronjob or do an update via typo3_console, which does this at regular intervals. Zabbix would then recognize the result and tell you if everything is still ok.

**Comment by svewap** [comment]
Shall we close it?

**Comment by twixwix** [comment]
Yes of course answer is perfect. #ThumbUp
