### ISSUE TITLE
GetProgramVersion always fails

### ISSUE THREAD

**Issue by twaurisch** [svewap/zabbix_client#21]
With TYPO3 version 9.5.26 the operation GetProgramVersion always fails, because the ExtConfiguration returns no program path.

Since TYPO3 version 9.0 the extension configuration ist stored in an array, see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Feature-82254-StoreExtensionConfigurationAsPlainArray.html

Contrary to what is stated in the documentation, the array keys for "directories" are stored without the dot `.` at the end of a key. It seems the usage of the dot is only required if the `unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']...)` -method is used.
As already mentioned in this case the documentation is wrong or at least confusing. (https://docs.typo3.org/m/typo3/reference-coreapi/9.5/en-us/ExtensionArchitecture/ConfigurationOptions/Index.html)

**Solution:**
Remove the dot `.` in EXT:zabbix_client/Classes/Operation/GetProgramVersion.php at line 38

**Comment by svewap** [comment]
Thank you. Fixed in next release.
