### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by janisint** [svewap/zabbix_client#23]
Hey
We plan to use Zabbix to monitor our TYPO3 projects soon. For this, we would really appreciate a new release of this extension, since the latest release is almost one year old. We would love to use all the new functions added in the meantime in an official release.

What do you think about it?

Thanks,
Janis

**Comment by svewap** [comment]
I will make a new release soon

**Comment by janisint** [comment]
Closed since a new release has now been published: [https://extensions.typo3.org/extension/zabbix_client#v0.2.10](https://extensions.typo3.org/extension/zabbix_client#v0.2.10)
