### ISSUE TITLE
typo3.xml for Zabbix 5.4

### ISSUE THREAD

**Issue by aliessmann** [svewap/zabbix_client#28]
I want to use Zabbix 5.4 but the typo3.xml is for Version 5.2. When will it be updated? Is there any way, to update it myself?

**Comment by svewap** [comment]
did you try to import it?

**Comment by aliessmann** [comment]
Yes, I tried by changing the version number in the XML, but there are structural Problems in the file (missing nodes, false nodes, etc.). An Import was not possible.

**Comment by Terminator81** [comment]
i have tried the same with a fresh 5.4 installation 

Import failed
Cannot import template "Template TYPO3 9-11", linked template "Template App HTTP Service" does not exist.

can you help me out? :)

**Comment by svewap** [comment]
@Terminator81 I see there is a problem in the template dependencies. I think your HTTP Template is called "HTTP Service" like in https://github.com/zabbix/zabbix/blob/master/templates/classic/template_app_http_service.yaml ?

**Comment by Terminator81** [comment]
so if i try to import these file:
https://i.imgur.com/fYfZZwe.png

**Comment by svewap** [comment]
I updated my templates to be more compatible to the official templates: Please try: https://github.com/svewap/zabbix_client/wiki

**Comment by Terminator81** [comment]
it works :)
