### ISSUE TITLE
TYPO3 IPTC preservation

### ISSUE THREAD

**Issue by Terminator81** [svewap/zabbix_client#29]
short question, how can i fix this:

**TYPO3 IPTC preservation**

what setting must be done?

**Comment by svewap** [comment]
You have to set this value:
`[GFX][processor_stripColorProfileCommand] = +profile '!iptc,*'`

**Comment by Terminator81** [comment]
works ...thanks

**Comment by Terminator81** [comment]
Is there anything special to consider with version 12?

The "old" template is still used on the server
