### ISSUE TITLE
"Undefined array key" error in class ManagerFactory

### ISSUE THREAD

**Issue by christianbltr** [svewap/zabbix_client#31]
## Bug description

In a TYPO3 11 / PHP 8 environment an error is logged to the TYPO3 Administration log every time the Zabbix Client is accessed.

This results in hundreds of thousands of log entries even after a short time because Zabbix calls the Zabbix Client every few seconds.

## Environment

* TYPO 11.5.13
* PHP Version 8.0.20 

## Details

The logged error is:

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Undefined array key "extConf" in [...]/typo3conf/ext/zabbix_client/Classes/ManagerFactory.php line 41 | TYPO3\CMS\Core\Error\Exception thrown in file [...]/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 137. Requested URL: https://[...]/zabbixclient/?operation=GetLogResults&filter=ServiceUnavailableException
```

## Possible solution

The reason seems to be in line 41 in the `ManagerFactory` class:

```
        $this->extConf = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['zabbix_client']);
```

The array key `$GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['zabbix_client']` seems not to be correct, it should rather be `($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['zabbix_client']`

Also my IDE reports that `$this->extConf` is never read so I think that line can just be removed.

## Workaround

Add this lines to the `ext_localconf.php` of your site package extension:

```
(static function() {
    // Workaround for zabbix_client error
    $GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['zabbix_client'] = 'a:0:{}';
})();
```

**Comment by svewap** [comment]
This problem has now been solved due to a code update
