### ISSUE TITLE
Change Template hoste urls 

### ISSUE THREAD

**Issue by rengaw83** [svewap/zabbix_client#4]
Hi,

the url for the http agent in the template is defined as follows:

```xml
<url>https://{HOST.HOST}/zabbixclient/</url>
```

HOST.HOST is the name of the host entry of zabbix.  
i think it would be better to use HOST.CONN.
```xml
<url>https://{HOST.CONN}/zabbixclient/</url>
```
Than the connection setting of the host will be used to build the url.

i normaly use the ip to connect the server. when i has to put the ip to the name of my host entry the listing is very confusing.

**Comment by svewap** [comment]
Will be fixed in next release: 52f10b798a709781bc6a82fe1afbd97a24e364e9
