### ISSUE TITLE
Broken integration to Crowdin

### ISSUE THREAD

**Issue by prathers** [svewap/zabbix_client#43]
There is an unconfigured branch to the Crowdin integration that need some attention: https://crowdin.com/project/typo3-extension-zabbixclient/apps/system/github

**Comment by prathers** [comment]
https://github.com/WapplerSystems/zabbix_client/issues/43

**Comment by svewap** [comment]
Fixed, but there is nothing that can be translated ;-)

**Comment by prathers** [comment]
May I suggest that we delete the project at Crowdin unless you plan to have labels to translate in the future? No need for taking up space in the TYPO3 platform, if not necessary.

**Comment by svewap** [comment]
Okay, I agree with that. My plan used to look different, but now I don't see any possibility of translating the client.

**Comment by prathers** [comment]
Thanks - I've removed the project
