### ISSUE TITLE
Configuration HasFailedSchedulerTask no longer in Template

### ISSUE THREAD

**Issue by secured** [svewap/zabbix_client#44]
Hi,

the zabbix template yaml no longer provides the configuration for HasFailedSchedulerTask.
The PHP class is still there: Classes/Operation/HasFailedSchedulerTask.php

Is there a reason why this check is no longer available?

Also the template name still states: "Template TYPO3 9-11" while the filename is up to date: 9-12.yaml

**Comment by svewap** [comment]
The check had an error but is now fixed for TYPO3 12. I updated the template for zabbix 7. The name will be updated in the next releases. But you can use this check by modifying your zabbix template.
