### ISSUE TITLE
Broken HasFailedSchedulerTask operation

### ISSUE THREAD

**Issue by r3h6** [svewap/zabbix_client#45]
https://github.com/WapplerSystems/zabbix_client/blob/98f1a3ac2a3c6b18157642e921bd94c12eef2475/Classes/Operation/HasFailedSchedulerTask.php#L47

fetchFirstColumn(0) returns an array which produces always true as operation result. According documentation fetchOne() should be used to get a scalar value.

TYPO3 v12
PHP 8.2

**Comment by svewap** [comment]
Is fixed in next release
